/****************************************************************
 * Copyright (C) 2018
 *    Computer Graphics Support Group of 30 Phys-Math Lyceum
 ****************************************************************/

/* FILE NAME   : SHAPES.H
 * PURPOSE     : Definition shapes.
 *               Header Module.
 * PROGRAMMER  : CGSG'2018
 *               MK5.
 * LAST UPDATE : 25.07.2018
 * NOTE        : Module namespace 'mert'.
 *
 * No part of this file may be changed without agreement of
 * Computer Graphics Support Group of 30 Phys-Math Lyceum.
 */

#ifndef __SHAPES_H_
#define __SHAPES_H_

#include "SHAPE.H"
#include "SPHERE.H"
#include "BOX.H"
#include "PLANE.H"
#include "TOR.H"

#endif /* __SHAPES_H_ */

/* END OF 'SHAPES.H' FILE */